#!/usr/bin/env bash
# shellcheck shell=bash
# Module paths are resolved at runtime through $SCRIPT_DIR, so shellcheck
# cannot follow the sources below statically.
# shellcheck disable=SC1090,SC1091

###############################################################################
# Script:        scripts/install.sh
# Description:   Interactive installer for Nerd Fonts using Homebrew and fzf.
#
# Requirements:
#   - Bash (recommended: 4.x+; compatible with the macOS default bash 3.2)
#   - Homebrew (https://brew.sh)
#   - fzf (installed automatically via Homebrew if missing)
#
# Usage:
#   ./scripts/install.sh [OPTIONS]
#
# Options:
#   (default)              Interactive fzf multi-select installation.
#   --all                  Install all available Nerd Fonts (non-interactive).
#   --fonts "FONT[,FONT]"  Install the named fonts (non-interactive).
#   --list                 Print available Nerd Fonts and exit.
#   --installed            Print installed Nerd Fonts casks and exit.
#   --uninstall [all|LIST] Uninstall fonts (interactive, all or named list).
#   --backend auto|brew|pacman|direct  Installation backend (default: auto).
#   --dry-run              Print what would be done without touching Homebrew.
#   --yes                  Reserved: accept future prompts (no effect yet).
#   --quiet                Suppress step/success/warning messages (QUIET=1 too).
#   --no-color             Disable colored output (NO_COLOR is honored too).
#   --version              Print version information and exit.
#   -h, --help             Show this help message and exit.
#
# Default behavior:
#   - Discover available Nerd Fonts casks via Homebrew.
#   - Present the list in fzf for multi-selection (TAB to select, ENTER to confirm).
#   - Install all fonts selected in fzf using Homebrew casks.
#
# Exit codes:
#   0   Success.
#   1   Invalid argument, usage or validation error.
#   2   Missing dependency (Homebrew not found, fzf could not be installed).
#   3   No Nerd Fonts found or available for the requested operation.
#   4   Partial failure: some fonts failed to install or uninstall.
#
# Structure:
#   This script is a thin development entrypoint. It resolves its own
#   directory, sources the modules below (in this exact, dependency order)
#   and hands control over to main():
#
#     scripts/lib/constants.sh        # Shared constants (version, options, colors)
#     scripts/lib/util.sh             # Maps/lists helpers and dispatch utilities
#     scripts/lib/log.sh              # Logging helpers and utilities
#     scripts/lib/cli.sh              # CLI state, argument parsing/validation and help
#     scripts/lib/platform.sh         # OS detection and backend resolution
#     scripts/lib/deps.sh             # Backend-aware dependency management
#     scripts/lib/fonts.sh            # Font discovery/selection and batch dispatch
#     scripts/lib/backends/brew.sh    # Homebrew backend
#     scripts/lib/backends/pacman.sh  # Arch Linux backend
#     scripts/lib/backends/direct.sh  # Direct GitHub release downloads backend
#     scripts/lib/main.sh             # main(): action dispatch and workflow
#
#   A single-file bundle is generated by scripts/build.sh into dist/install.sh
#   (for curl | bash usage). The bundle embeds all modules above and sets
#   NERDFONTS_BUNDLED=1, which makes this sourcing step be skipped.
#
# Notes:
#   - Intended for macOS and Linux environments. Backends: brew, pacman or
#     direct downloads from the official releases; "auto" detects the best one.
#   - This script only installs fonts; it does not change your terminal/editor
#     configuration to start using them.
###############################################################################

# Enable strict error handling:
# - -e: exit on any command failure
# - -u: treat unset variables as errors
# - -o pipefail: propagate failures in pipelines
set -euo pipefail
IFS=$'\n\t'

# -----------------------------------------------------------------------------
# Entrypoint bootstrap
# -----------------------------------------------------------------------------

# Resolve the directory containing this script, following symlinks so the lib
# modules can be sourced regardless of how the script was invoked.
SOURCE="${BASH_SOURCE[0]:-$0}"
while [[ -L "$SOURCE" ]]; do
  SOURCE_DIR=$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)
  SOURCE=$(readlink "$SOURCE")
  case $SOURCE in
  /*) ;;
  *) SOURCE="$SOURCE_DIR/$SOURCE" ;;
  esac
done
SCRIPT_DIR=$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)

# Load library modules in dependency order. Skipped when running from the
# single-file bundle (dist/install.sh), which already embeds every module.
if [[ -z "${NERDFONTS_BUNDLED:-}" ]]; then
  source "$SCRIPT_DIR/lib/constants.sh"
  source "$SCRIPT_DIR/lib/util.sh"
  source "$SCRIPT_DIR/lib/log.sh"
  source "$SCRIPT_DIR/lib/cli.sh"
  source "$SCRIPT_DIR/lib/platform.sh"
  source "$SCRIPT_DIR/lib/deps.sh"
  source "$SCRIPT_DIR/lib/fonts.sh"
  source "$SCRIPT_DIR/lib/backends/brew.sh"
  source "$SCRIPT_DIR/lib/backends/pacman.sh"
  source "$SCRIPT_DIR/lib/backends/direct.sh"
  source "$SCRIPT_DIR/lib/main.sh"
fi

# -----------------------------------------------------------------------------
# Script execution
# -----------------------------------------------------------------------------
main "$@"
